# Generated by Django 6.0.3 on 2026-03-24 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_stock_product_quantity_remove_product_battery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
    ]
